import {useCallback,useEffect,useState} from "react";
import {LogIn,RefreshCw} from "lucide-react";
import {command,subscribe} from "./bridge";
import {errorOf} from "./types";
type Profile={mode:"official"|"api";revision:string;initialized:boolean;conflict:string|null;files:{role:string;exists:boolean;revision:string}[];warnings:string[]};
type Login={phase:string;authenticated:boolean;error:string|null};
export default function ClaudeProfile({disabled=false,beforeChange,onChanged,notify}:{disabled?:boolean;beforeChange?:()=>Promise<boolean>;onChanged?:()=>void;notify:(text:string)=>void}){
 const [profile,setProfile]=useState<Profile|null>(null),[login,setLogin]=useState<Login|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const reload=useCallback(async()=>{try{setProfile(await command<Profile>("get_claude_profile"));}catch(e){setError(errorOf(e).message);}},[]);
 useEffect(()=>{let gone=false;const cleanup:(()=>void)[]=[];void reload();for(const [event,fn] of [["claude-profile-state",setProfile],["claude-login-state",setLogin]] as const){void subscribe<Profile|Login>(event,s=>{if(!gone)(fn as (s:Profile|Login)=>void)(s);}).then(c=>gone?c():cleanup.push(c));}void subscribe<{clientId:string}>("config-state",s=>{if(!gone&&s.clientId==="claude")void reload();}).then(c=>gone?c():cleanup.push(c));void command<Login>("claude_login_status").then(s=>{if(!gone)setLogin(s);}).catch(e=>{if(!gone)setError(errorOf(e).message);});return()=>{gone=true;cleanup.forEach(c=>c());};},[reload]);
 const run=async(fn:()=>Promise<void>)=>{if(busy)return;setBusy(true);setError("");try{await fn();}catch(e){setError(errorOf(e).message);await reload();}finally{setBusy(false);}};
 const switchMode=async(mode:Profile["mode"])=>{if(!profile||profile.mode===mode)return;if(beforeChange&&!await beforeChange())return;await run(async()=>{setProfile(await command<Profile>("switch_claude_profile",{mode,expectedRevision:profile.revision}));onChanged?.();notify(`Claude ${mode==="official"?"官方":"API"}配置已启用，请重新打开 Claude Code`);});};
 const waiting=login?.phase==="waiting"||login?.phase==="cancelling";
 return <div className="claude-profile"><div className="claude-profile-controls"><div className="segmented" aria-label="Claude 配置来源">{([["official","官方"],["api","API"]] as const).map(([mode,label])=><button key={mode} type="button" aria-pressed={profile?.mode===mode} disabled={disabled||busy||waiting||!profile||!!profile.conflict} onClick={()=>void switchMode(mode)}>{label}</button>)}</div>{profile?.mode==="official"&&(waiting?<button type="button" disabled={login?.phase==="cancelling"} onClick={()=>void run(async()=>{await command("cancel_claude_login");setLogin(s=>s?{...s,phase:"cancelling"}:s);})}>取消登录</button>:<button type="button" disabled={busy||disabled||!!profile.conflict} onClick={()=>void run(async()=>setLogin(await command<Login>("start_claude_login")))}><LogIn size={15}/>{login?.authenticated?"已登录官方账号":"官方登录"}</button>)}{profile?.mode==="official"&&<button className="icon-button" type="button" disabled={busy||waiting} aria-label="刷新官方登录状态" onClick={()=>void run(async()=>setLogin(await command<Login>("claude_login_status")))}><RefreshCw size={15}/></button>}{waiting&&<span role="status">等待浏览器授权</span>}{profile?.conflict&&<button type="button" disabled={busy||disabled} onClick={()=>void run(async()=>{setProfile(await command<Profile>("recover_claude_profile"));onChanged?.();})}>恢复事务</button>}</div>{(error||profile?.conflict||login?.error)&&<p role="alert" className="form-error">{error||profile?.conflict||login?.error}</p>}{!!profile?.warnings.length&&<details className="claude-profile-warning"><summary>检测到外部覆盖 · {profile.warnings.length}</summary><ul>{profile.warnings.map(w=><li key={w}>{w}</li>)}</ul></details>}</div>;
}
