import {useEffect,useMemo,useState} from "react";
import {Download,FolderOpen,Plus,RefreshCw,Search,Trash2,Upload,X} from "lucide-react";
import {command,subscribe} from "./bridge";
import {errorOf} from "./types";
import {confirmAction} from "./confirmation";
import {Drawer} from "./Usage";
import type {PricingConfig,PricingView} from "./usage-types";
const fields=[["input_cost_per_token","输入"],["output_cost_per_token","输出"],["cache_read_input_token_cost","缓存读取"],["cache_creation_input_token_cost","缓存写入"]];
function millions(v:unknown){return v==null?"—":(Number(v)*1e6).toLocaleString("zh-CN",{maximumFractionDigits:8});}
export default function Pricing({onDirtyChange}:{onDirtyChange?:(dirty:boolean)=>void}){
 const [view,setView]=useState<PricingView|null>(null),[search,setSearch]=useState(""),[editor,setEditor]=useState<string|null>(null),[sync,setSync]=useState(false),[error,setError]=useState(""),[busy,setBusy]=useState(false),[limit,setLimit]=useState(50);
 useEffect(()=>{let disposed=false,off=()=>{};const read=()=>void command<PricingView>("get_pricing").then(s=>{if(!disposed)setView(s);}).catch(e=>!disposed&&setError(errorOf(e).message));read();void subscribe("pricing-state",read).then(c=>disposed?c():off=c);return()=>{disposed=true;off();};},[]);
 useEffect(()=>{onDirtyChange?.(editor!==null||sync);return()=>onDirtyChange?.(false);},[editor,sync,onDirtyChange]);
 const save=async(config:PricingConfig)=>{if(!view)return;setBusy(true);setError("");try{setView(await command<PricingView>("configure_pricing",{config,expectedRevision:view.revision}));}catch(e){setError(errorOf(e).message);try{setView(await command<PricingView>("get_pricing"));}catch{}throw e;}finally{setBusy(false);}};
 const action=async(name:string)=>{setBusy(true);setError("");try{const result=await command<PricingView>(name);if(result?.models)setView(result);}catch(e){setError(errorOf(e).message);}finally{setBusy(false);}};
 const models=useMemo(()=>Object.keys(view?.models??{}).filter(m=>m.toLowerCase().includes(search.toLowerCase())).sort(),[view,search]);
 const importFile=async(file:File|undefined)=>{if(!file||!view)return;if(file.size>8*1024*1024){setError("价格文件超过 8 MB");return;}try{const data:unknown=JSON.parse(await file.text());if(!data||typeof data!=="object"||Array.isArray(data))throw new Error("请选择模型价格 JSON 对象");await save({...view.config,fixed:{...view.config.fixed,...data as PricingConfig["fixed"]}});}catch(e){setError(errorOf(e).message);}};
 return <section className="usage-pricing"><div className="usage-pricing-toolbar"><label className="usage-search"><Search size={15}/><input aria-label="搜索价格模型" placeholder="搜索模型" value={search} onChange={e=>{setSearch(e.target.value);setLimit(50);}}/></label><button disabled={busy} onClick={()=>setEditor("")}><Plus size={15}/>添加</button><label className="usage-import" tabIndex={0}><Upload size={15}/>导入<input aria-label="导入价格 JSON" type="file" accept="application/json,.json" onChange={e=>{void importFile(e.target.files?.[0]);e.target.value="";}}/></label><button onClick={()=>setSync(true)}>自动同步</button><details className="usage-more"><summary aria-label="定价更多操作">•••</summary><div><button onClick={()=>void action("open_pricing_directory")}><FolderOpen size={14}/>打开定价目录</button><button onClick={()=>void action("reload_pricing")}><RefreshCw size={14}/>重新载入</button><button onClick={()=>void action("update_pricing")} disabled={busy}><Download size={14}/>立即更新</button></div></details></div>
 {(error||view?.error)&&<p role="alert" className="form-error">{error||view?.error}</p>}
 <div className="usage-table-scroll"><table className="usage-table usage-price-table"><thead><tr><th>模型</th>{fields.map(([k,n])=><th key={k}>{n} / 百万</th>)}<th>来源</th><th/></tr></thead><tbody>{models.slice(0,limit).map(id=>{const p=view!.models[id],fixed=id in view!.config.fixed;return <tr key={id}><td><button className="usage-model-button" onClick={()=>setEditor(id)}>{id}</button></td>{fields.map(([k])=><td key={k}>{millions(p[k])}</td>)}<td>{fixed?"固定":view!.config.excluded.includes(id)?"已排除":"Sub2API"}</td><td><button className="icon-button" aria-label={`删除价格 ${id}`} onClick={()=>void confirmAction(`删除 ${id} 的价格？`).then(ok=>{if(ok){const config=structuredClone(view!.config);delete config.fixed[id];config.excluded=[...new Set([...config.excluded,id])];void save(config).catch(()=>{});}})}><Trash2 size={14}/></button></td></tr>;})}</tbody></table></div>
 {models.length>limit&&<button className="usage-load-more" onClick={()=>setLimit(limit+100)}>显示更多（{models.length-limit}）</button>}
 <details className="usage-price-source"><summary>{view?.source??"价格来源"}</summary><dl className="usage-detail-grid"><dt>最后检查</dt><dd>{view?.checkedAt?new Date(view.checkedAt).toLocaleString():"尚未检查"}</dd><dt>价格更新</dt><dd>{view?.updatedAt?new Date(view.updatedAt).toLocaleString():"—"}</dd><dt>SHA-256</dt><dd>{view?.version}</dd></dl></details>
 {editor!==null&&view&&<PriceEditor key={editor} model={editor} view={view} busy={busy} save={save} onClose={()=>setEditor(null)}/>}
 {sync&&view&&<SyncPrices view={view} busy={busy} save={save} update={()=>action("update_pricing")} onClose={()=>setSync(false)}/>}
 </section>;
}
function PriceEditor({model,view,busy,save,onClose}:{model:string;view:PricingView;busy:boolean;save:(c:PricingConfig)=>Promise<void>;onClose:()=>void}){
 const [name,setName]=useState(model),[values,setValues]=useState(()=>Object.fromEntries(fields.map(([k])=>[k,view.models[model]?.[k]==null?"":String(Number(view.models[model][k])*1e6)]))),[advanced,setAdvanced]=useState(JSON.stringify(view.models[model]??{},null,2)),[error,setError]=useState("");
 const submit=async(e:React.FormEvent)=>{e.preventDefault();try{const id=name.trim();if(!id)throw new Error("请输入模型 ID");const p=JSON.parse(advanced) as Record<string,unknown>;if(!p||typeof p!=="object"||Array.isArray(p))throw new Error("高级价格必须为 JSON 对象");for(const[k]of fields){if(values[k]===""){delete p[k];continue;}if(!/^\d+(\.\d+)?$/.test(values[k]))throw new Error("单价必须为非负数");const [whole,fraction=""]=values[k].split(".");const digits=whole.padStart(7,"0");p[k]=digits.slice(0,-6)+"."+digits.slice(-6)+fraction;}await save({...view.config,fixed:{...view.config.fixed,[id]:p},excluded:view.config.excluded.filter(v=>v!==id)});onClose();}catch(e){setError(errorOf(e).message);}};
 return <Drawer title={model?"编辑价格":"添加价格"} onClose={onClose}><form onSubmit={e=>void submit(e)}><label className="usage-field">模型 ID<input required value={name} disabled={!!model} onChange={e=>setName(e.target.value)} /></label><div className="usage-price-fields">{fields.map(([k,n])=><label className="usage-field" key={k}>{n} · USD / 百万 Token<input inputMode="decimal" value={values[k]} onChange={e=>setValues({...values,[k]:e.target.value})} placeholder="未定价"/></label>)}</div><details><summary>分层、缓存时长与媒体价格</summary><textarea aria-label="高级价格 JSON" className="usage-json" value={advanced} onChange={e=>setAdvanced(e.target.value)} spellCheck={false}/></details>{error&&<p className="form-error" role="alert">{error}</p>}<div className="usage-form-actions">{model&&<button type="button" disabled={busy} onClick={async()=>{try{const c=structuredClone(view.config);delete c.fixed[model];c.excluded=c.excluded.filter(m=>m!==model);await save(c);onClose();}catch(e){setError(errorOf(e).message);}}}>恢复自动价格</button>}<button type="button" onClick={onClose}>取消</button><button className="primary" disabled={busy}>保存</button></div></form></Drawer>;
}
function SyncPrices({view,busy,save,update,onClose}:{view:PricingView;busy:boolean;save:(c:PricingConfig)=>Promise<void>;update:()=>Promise<void>;onClose:()=>void}){
 const [draft,setDraft]=useState(()=>structuredClone(view.config)),[search,setSearch]=useState(""),[error,setError]=useState("");const ids=Object.keys(view.models).filter(id=>id.toLowerCase().includes(search.toLowerCase())).sort();const selected=new Set(draft.selected??Object.keys(view.models));
 const toggle=(id:string,yes:boolean)=>{const next=new Set(selected);if(yes)next.add(id);else next.delete(id);setDraft({...draft,selected:[...next],excluded:draft.excluded.filter(m=>m!==id)});};
 return <Drawer title="价格自动同步" onClose={onClose}><label className="usage-setting">自动更新<input type="checkbox" checked={draft.autoUpdate} onChange={e=>setDraft({...draft,autoUpdate:e.target.checked})}/></label><input aria-label="搜索同步模型" placeholder="搜索模型" value={search} onChange={e=>setSearch(e.target.value)}/><div className="usage-actions"><button onClick={()=>setDraft({...draft,selected:[...new Set([...selected,...ids])],excluded:draft.excluded.filter(id=>!ids.includes(id))})}>全选结果</button><button onClick={()=>setDraft({...draft,selected:[...selected].filter(id=>!ids.includes(id))})}>清空结果</button><button onClick={()=>setDraft({...draft,selected:null,excluded:[]})}>全部模型</button></div><div className="usage-price-picker">{ids.map(id=><label key={id}><input type="checkbox" checked={selected.has(id)&&!draft.excluded.includes(id)} onChange={e=>toggle(id,e.target.checked)}/><span>{id}</span><button className="icon-button" title="排除自动同步" aria-label={`排除 ${id}`} onClick={()=>setDraft({...draft,excluded:[...new Set([...draft.excluded,id])]})}><X size={13}/></button></label>)}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="usage-form-actions"><button disabled={busy} onClick={()=>void update()}>立即更新</button><button disabled={busy} className="primary" onClick={async()=>{try{await save(draft);onClose();}catch(e){setError(errorOf(e).message);}}}>保存</button></div></Drawer>;
}
